# Generated by Django 5.2.12 on 2026-03-25 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="longtitude",
            new_name="longitude",
        ),
    ]
