# Generated by Django 5.2.12 on 2026-03-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_location_latitude_remove_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='property.property'),
        ),
    ]
